language: r
cache: packages
dist: trusty
sudo: false
warnings_are_errors: true
bioc_required: true
before_install:
- Rscript -e 'update.packages(ask = FALSE)'
r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"
notifications:
  slack:
    secure: IeQ8g+NQY9yjA3qHwDfwBjLVSfFXqLvvXflKssI/qY6HhTP3GV795huSZZWjsGoABY0VTo1YQiL2f32kRb7AHREiIN1NM70XrOTxxB+FV2nVd/bjvUndbiVUAqy37J98WCKQ7agZwOMor2QZ6z8azlQCPmbOmfNgs2vIvKsVzr6tBCZuWUIBh9PdaXPhvaCHJtTyAlVK+l2SZD2oS9CQXhIp7GxIkWeKaGITPLRU39xdaQG8WCxw8HwytMaPEh07TYj6cGTDhpMhZFOdQ5KirjB62EOM3U9z4FFoZZAjI2t9FxZRz/nyzGGEN+SyRHD3WP+72HGXBcpaPOxl0pQoQ2yG4+8mV7JhxTkqjnAT6Q0dDr8vtoxqnlg6gi3JqcfuYI7swWLx93H7pjdaYwcj1fSJX5E6sRq+UyLwNVJuae3EFMtrndZd5MxBEy83dPn0yo4w3sUzF5xZrfHLfI5969YgG3+iXW+KZE1qsnbXKJdXG4VfJ+bWNhddzwGQ2pxkAR0m18zFKlW2nEnjs10q6MFiq1hb4VjOcDfLbzahlHQJt4SMT3iwBmvEgJeZGIgg6DMQGqFaO0ybwKWrxmgYHPMRKO8u8xTT0ntKu2M3+p5c7JmoGaTCuJ8dmu+RTZMO8cFJVbzzxXdpDB1Nb1jN6lUHvRNQ6xXd6Hg8PdITtbc=
    on_success: always

