language: r
cache: packages
dist: trusty
sudo: false
warnings_are_errors: true
bioc_required: true
before_install:
- Rscript -e 'update.packages(ask = FALSE)'
r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"
notifications:
  slack:
    rooms:
      secure: Wjj/W85j+1xgyut5yrfSrm/XhPJGThFvRt7lA586Pl0479LqXfL/rCbjlqMLg730XhrrUmYAbvQrWlXpCkQC+gwSlV4LtHq5+XnUbAgZdwJu/07SkfZ0Xj09cF6/KzcFzlr+B38hJrlHKGvZHDKvKye43Uf9Dl5FNyk1fNi5rIgQMVPGKR3ZaTFT4RGzdT5SzsGbsTX3tdepaI5t09cQ8MUOu+Uh7CotPptAGZEswx7V80PNs3otKfCFq6zLop+G2mTChv1e+RDIWsEDh6Ey0TOm0Tw0wFhEnDbhONToHI7aT8aB7nQyRQt61ABftxwOA+raVL8pUVqkzQnmBWsRf5KNryiYEq3NaCeDDVVSPxrsQdC6MRfzCPFRgDi2t0ILpsjYYSMj6APksuBuTKrZvzAc0NdFaMeaBvnmi7MZU3vjx63MFXSOm5gyb+E5ErEyEwr+0PjkjlZdfR7pU9mxQjpLX46nksyteV/kEukbK+j8hrMvnBL3XA9bew8/lkDx8/eicpZKTHfB4i9LOtYhNFBHoX2pGqH7sgvJg8BNL+kQW3hArcQRiJfi9ttiOBsvGDpmMUD6dZ4SW/dHs47u2RYIR9w8YT9QykgE0STtItZ2yZQXX/MHtCQslcwimQDoxav5+sSXgGlod3QaywXDADcasAf8iXzEv51n8vVs4zI=
