language: r
cache: packages
dist: trusty
sudo: false
warnings_are_errors: true
bioc_required: true
before_install:
- Rscript -e 'update.packages(ask = FALSE)'
r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"
notifications:
  slack:
    secure: ci8yd/ArjReq3dVbeyUHpsMYeTHG12IacML2zCS+5Ay3Kx1XJTwDes8N4TBLFm34+XSPtchLICSu19JoMMNODGpK+G2GX8K3CeklEBR5Ww5ixzDzhoPHH3yt+jeDGFxDMN/lVofJtisIvAQ6BxTQwbw9AkCpQZsC9ZzNO3g4qZg/JMBuiz7A7xdngklmzm9Qdim+89BWyEZFOXTFRpCLeqN2EeO0JBkgD9l8FKyY4Q51sxCxPfFSDjU6y2weLhcmnAYZbqgPBMDHyGFg2FctUsdoaLc7vekJF4+AWK4ErXP/toPNN8qJBsnJnqjW4hPOXQeFNA8mjVOsWFVyLaWFuquWbMjUO6k6GhAaaAd0qMf3rb6Qqp1EnCFkLF13DMnmRtNPlQ7gGLr8RInpveFa96aldryqC+mqyaoiLV/RI+vH+gvc/Z2Fu60c5PYLVNgkWsvVT2MfseNKMQud9kKczwIGz6t0DobEEGjk+z55z0gegtAz7QaAOX8PotLKgDunEuGJoR8b33Ebo2490L/Aggv0mshhbs3QrkA+y2Wc6iLRzaEMDJXxFhmI3hThDRDk/zPkpQjjG9C2AzGSckUeknKemdag95BMh6mWhbFBGlMWF5EMQptgQS7PIUS+t+JXiniliVRkDcDA+71o4aP/P19y9mRRFhDUGZUytpuFBrs=
